### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by santiagosayshey** [santiagosayshey/OOProject#4]
**_Project Plan_**
_Due Date: Friday Week 9_

_Tasks:_
- [x] Use Case Description [ Core idea, Functionalities, User interaction ] _5 Points_
- [x] Identify classes _5 Points_
- [x] Identify class data and function members _3 Points_
- [x] Find inheritance and aggregation relationships between classes (?Mindmap) _5 Points_
- [x] Time plan _3 Points_
- [x] Description of user interface and how user will interact with system _2 Points_
- [x] Unit Testing and debugging _2 Points_
